server:
  port: 8080

jwt:
  secret: "5T2gH5f'<Ny<uQY^}0rNm01UK/,]V|r#J54x4c_mBE~/%W#qE/58T?E27q[os{}"
  expiration: 86400000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/BlogDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB



  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


